### PR TITLE
Improved Inventory

### PR DESCRIPTION
**Pull request by ortegamarcel**
improved-inventory
improved-inventory-v2
improved-inventory-diagrams-and-formulae

# Improved Inventory
* fixed columns of Valuables in inventory (no longer misaligned)  (see screenshot)
* reorganized inventory  (see screenshot)
    - introduced new sub types for valuables: quest-item and alchemical-item
    - disabled sub types of valuables: service and lodging (In my opinion they shouldn't be visible in the inventory, therefore I don't need them)
    - valuables are now organized into several sections: quest items, general, food and drinks, toolkits, clothing & containers, mounts, mount accessories
    - added new section "Alchemy" to the right column" with following sub sections: Alchemical Items, Oils, Witcher Potions & Mixtures, Mutagens, Alchemical Treatments, Substances  (see screenshot)
    - Alchemical Treatmenst are no longer shown at the Components section
* improved details panels for items (see screenshot)
    - descriptions and effects are no longer centered but left-aligned
    - added toxicity to potions and decoctions
    - fixed "Time" of potions, decoctions and oils, it is acutually the duration and not the crafting time
* Added subsections to "Components" (see Screenshot)
* Mutagens now show "Effects" and "Minor Mutations" instead of "Type" (Color) and "Source".
* If a sub section does not contain an item, the section won't appear.
* Added subsections for formulae: Alchemical Item Formulae, Witcher-Potion Formulae, Witcher-Decoction Formulae, Oil Formulae
    - showing description, if it has one
    - aligned icons (craft, edit, delete) at the top
    - showing level
* Added subsections for diagrams: Component Diagrams, Weapon Diagrams, Armor Diagrams, Elderfolk Weapon Diagrams, Elderfolk Armor Diagrams, Ammunition Diagrams, Bomb Diagrams and Trap Diagrams
    - showing level
* All "+"-icons work again
    - also when migrating "old" character sheets, some valuables and diagrams could have an empty subtype. There are now also shown
* fixed critical issue where some character sheets would not open

It comes with english and german translation.

### CODE REVIEW

**Comment by Melkkart** [comment]
Wonderful, I like the inventory always tidy, I have tried it and everything seems to work fine, thank you very much, there is a small recurring bug when attacking (for example with a sword) from the inventory, it does not re-roll the die if it is critical nor when it is a failure, I do not know if you could fix it, but do not worry, I do not want to bother you either, I will simply re-enable it from rollConfig.js. Again thank you very much for everything.

**Comment by ortegamarcel** [comment]
> Wonderful, I like the inventory always tidy, I have tried it and everything seems to work fine, thank you very much, there is a small recurring bug when attacking (for example with a sword) from the inventory, it does not re-roll the die if it is critical nor when it is a failure, I do not know if you could fix it, but do not worry, I do not want to bother you either, I will simply re-enable it from rollConfig.js. Again thank you very much for everything.

@Melkkart Yeah I already noticed it. I can also try to fix it. But I will do it in a separate PR.

I also noticed, that enhancements do not work. For now I don't show them in the Inventory for that reason. But I will also try to fix them.

**Comment by Melkkart** [comment]
Hi, something strange happened to us in the last game.
Some of my players couldn't open their character file, I tried to open it as GM and I couldn't either, so I decided to go back to the previous version, and yes, everything worked correctly, I don't know where the failure is, if it is some object, this afternoon I will try to find the specific failure and I will let you know, they are characters of a long campaign and they have many objects on them, some of them are even overloaded.
I will try to let you know as soon as possible and thanks.

**Comment by ortegamarcel** [comment]
> Hi, something strange happened to us in the last game. Some of my players couldn't open their character file, I tried to open it as GM and I couldn't either, so I decided to go back to the previous version, and yes, everything worked correctly, I don't know where the failure is, if it is some object, this afternoon I will try to find the specific failure and I will let you know, they are characters of a long campaign and they have many objects on them, some of them are even overloaded. I will try to let you know as soon as possible and thanks.

@Melkkart Oh okay, thanks. Can you send me the problematic character? (Export to JSON) So I can also take a look.

**Comment by Melkkart** [comment]
ok, 3 characters, so you can compare, but don't worry, when I get home I'll create copies, dividing their objects, I'm sure it must be some obejto.
At first I thought it was a full inventory, and I dragged a negatively charged object to unlock it, but it didn't work, so you will find some object in his inventory with negative weight. 

https://drive.google.com/file/d/1qN61n32qzvQEz_J4cTRRx8ABgapClNza/view?usp=sharing

**Comment by ortegamarcel** [comment]
@Melkkart Thanks. I tested it with your actors and indeed there seem to be an issue with the diagrams. Really strange. I could fix it, but I don't really understand what exactly was causing the problem, since it worked on my characters and I couldn't find a difference.

Anyway. It should work now. But you night take a look as well. Maybe you can find/understand the issue?! I'am very new to foundry (and TheWitcherTRPG).

**Comment by Melkkart** [comment]
I have reduced the error to the Diagrams, creating oils works correctly, creating Alchemy objects also, but if you have several recipes to create Weapons, armor or ammunition, the character sheet is locked and can no longer be opened.  And thks for the fix. :)

**Pull request merged**
